# Данный процесс проверяет, нормально ли инициализируется БД из скриптов, расположенных в папке database
name: Проверка деплоя БД

on:
  push:
    paths:
      - 'database/*'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'database/*'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Запуск инициализации БД
        run: docker-compose up postgres
      - name: Проверка на наличие ошибок
        run: docker-compose logs | grep ERROR && exit 1
