# Данный процесс проверяет, нормально ли инициализируется БД из скриптов, расположенных в папке database
name: Проверка деплоя БД

on:
  pull_request:
    paths:
      - 'database/**'
    branches:
      - main
    types:
      - opened
      - edited
  # Ручной запуск
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Запуск инициализации БД
        run: docker-compose up -d postgres
      - name: Проверка на наличие ошибок
      # Немножко костыль со sleep, знаю, но пока так. Можно использовать wait-for-it.sh
        run: sleep 10 && docker-compose logs | grep ERROR && exit 1 || exit 0
